//
//  VideoFilenameTests.swift
//  Subler
//
//  Test driver for the VideoFilename Swift port. Two modes:
//
//    parse-tests --parse <name>
//        Parses a single video name string (the string itself — not contents
//        of a file) and prints the result in the exact output format of the
//        original ParseFilename.pl, so the port can be diffed against perl.
//
//    parse-tests --corpus <corpus.txt> <expected.txt>
//        Parses every name in corpus.txt (one per line) and compares the
//        combined output (blocks separated by "---" lines) against
//        expected.txt, which was generated by running the perl script over
//        the same corpus. Exits non-zero on any mismatch.
//

import Foundation

/// Replicates ParseFilename.pl's output for a parsed filename
/// (perl's undef prints as an empty line).
func perlStyleOutput(_ file: ParsedVideoFilename) -> String {
    var lines: [String] = []
    if file.isTVShow {
        lines = ["tv", file.name ?? "", file.season ?? "", file.episode ?? ""]
    } else if file.isEpisode {
        lines = ["tv", file.name ?? "", file.season ?? "", file.episode ?? "", file.part ?? ""]
    } else if file.isMovie {
        lines = ["movie", file.movie ?? ""]
    } else {
        lines = ["unknown"]
    }
    return lines.joined(separator: "\n") + "\n"
}

@main
struct ParseTests {
    static func main() {
        run()
    }
}

private func run() {
    let arguments = CommandLine.arguments

    if arguments.count >= 3 && arguments[1] == "--parse" {
        print(perlStyleOutput(ParsedVideoFilename.parse(arguments[2])), terminator: "")
        exit(0)
    }

    if arguments.count >= 4 && arguments[1] == "--corpus" {
        guard let corpus = try? String(contentsOfFile: arguments[2], encoding: .utf8),
              let expected = try? String(contentsOfFile: arguments[3], encoding: .utf8) else {
            FileHandle.standardError.write("error: cannot read corpus or expected file\n".data(using: .utf8)!)
            exit(2)
        }

        let names = corpus.split(separator: "\n", omittingEmptySubsequences: true).map(String.init)
        let expectedBlocks = expected.components(separatedBy: "---\n").filter { !$0.isEmpty }

        guard names.count == expectedBlocks.count else {
            FileHandle.standardError.write(
                "error: corpus has \(names.count) entries but expected file has \(expectedBlocks.count) blocks\n"
                    .data(using: .utf8)!)
            exit(2)
        }

        var failures = 0
        for (name, expectedBlock) in zip(names, expectedBlocks) {
            let actual = perlStyleOutput(ParsedVideoFilename.parse(name))
            if actual != expectedBlock {
                failures += 1
                print("FAIL: \(name)")
                print("  expected: \(expectedBlock.replacingOccurrences(of: "\n", with: "\\n"))")
                print("  actual:   \(actual.replacingOccurrences(of: "\n", with: "\\n"))")
            }
        }

        if failures > 0 {
            print("\(failures) of \(names.count) filenames FAILED")
            exit(1)
        } else {
            print("all \(names.count) filenames OK")
            exit(0)
        }
    }

    FileHandle.standardError.write("""
    usage: parse-tests --parse <name>
           parse-tests --corpus <corpus.txt> <expected.txt>

    --parse   parse a video name string (not a file path to read)
    --corpus  compare parses of every name in corpus.txt to expected.txt

    """.data(using: .utf8)!)
    exit(2)
}
